version: '3'
services:
  bot:
    build: .
    image: netology/sokratbot
    command: ["sh", "docker-entrypoint.sh", "5433"]
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=davydenkovm
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=sokrat_db
    volumes:
      - sokrat_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    expose:
      - "5433"

volumes:
  sokrat_db:
